import { api } from "@/utils/api";
import { Conditional } from "@pandeymangg/react-conditional";
import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/navigation";

const Home: NextPage = () => {
  const { status } = useSession();
  const isAuthenticated = status === "authenticated";

  const router = useRouter();

  const { data } = api.collaboration.getAll.useQuery(undefined, {
    enabled: isAuthenticated,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full flex-col items-center">
        <div className="container grid h-96 place-items-center">
          <h2 className="text-subtext1 text-center text-4xl font-bold">
            Simple Docs home page...
          </h2>

          <div className="flex flex-col items-center justify-center">
            {data?.map((collab) => (
              <div key={collab.id}>
                <h2 className="text-subtext1 text-center text-4xl font-bold">
                  {collab.collaboratorId} requesting access for {collab.docId}
                </h2>
              </div>
            ))}
          </div>

          <div className="flex flex-col items-center justify-center">
            <Conditional
              condition={isAuthenticated}
              fallback={
                <button
                  className="btn-primary btn capitalize"
                  onClick={() => router.push("/login")}
                >
                  Log In
                </button>
              }
            >
              <button
                className="btn-primary btn capitalize"
                onClick={() => router.push("/dashboard")}
              >
                Dashboard
              </button>
            </Conditional>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
